import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const iranYekanXFont = localFont({
    src: [
        { path: "../fonts/IRANYekanXFaNum-Thin.woff", weight: "100" },
        { path: "../fonts/IRANYekanXFaNum-UltraLight.woff", weight: "200" },
        { path: "../fonts/IRANYekanXFaNum-Light.woff", weight: "300" },
        { path: "../fonts/IRANYekanXFaNum-Regular.woff", weight: "400" },
        { path: "../fonts/IRANYekanXFaNum-Medium.woff", weight: "500" },
        { path: "../fonts/IRANYekanXFaNum-DemiBold.woff", weight: "600" },
        { path: "../fonts/IRANYekanXFaNum-Bold.woff", weight: "700" },
        { path: "../fonts/IRANYekanXFaNum-ExtraBold.woff", weight: "800" },
        { path: "../fonts/IRANYekanXFaNum-Black.woff", weight: "900" },
        { path: "../fonts/IRANYekanXFaNum-ExtraBlack.woff", weight: "950" },
        { path: "../fonts/IRANYekanXFaNum-Heavy.woff", weight: "1000" },
    ],
    variable: "--font-iranYekanX",
});
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir='rtl'>
        <body
            className={`${iranYekanXFont.variable} font-iranYekanX`}
        >
        {children}
        </body>
        </html>
    );
}
